config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
   resources :reviews, only: [ :create, :new ]
  end
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    SEPCIALITY = ["chinese", "italian", "japanese", "french", "belgian"]
    has_many :reviews, dependent: :destroy
    validates :name, :address, presence: true
    validates :category, presence: true, inclusion: { in: SEPCIALITY }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

before_action :set_restaurants, only: :show

  def index
    @restaurants = Restaurant.all   
  end

  def show 
    @restaurant
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.create(restaurants_params)
  end

  private 

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurants
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def new
      @review = Review.new
      @restaurant = Restaurant.find(params[:restaurant_id])
    #   redirect_to restaurant_path(@restaurant)
    end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
    redirect_to restaurant_path(@restaurant)
    else
        render "restaurant/show"
    end
  end

private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1> Restaurants list </h1>


<ul>
<% @restaurants.each do |restaurant| %> 
<%= restaurant.name %>
<li>  <%= link_to "See details", restaurant_path(restaurant), class: "btn btn-primary"%> </li>
<% end %>

</ul>

app/views/restaurants/show.html.erb
<%= @restaurant.name %>
<%= @restaurant.address %>
<%= @restaurant.phone_number %>
<%= @restaurant.category %>
<% @restaurant.reviews.each do | review| %>
<p> Rating <%= review.rating %></p>
<p>  Review <%=review.content %></p>
<% end %>

<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.label :rating %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.label :content %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

<%= link_to "Go to home page", restaurants_path %>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.label :rating %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.label :content %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>